apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimiter-config
  namespace: ratelimiter
data:
  config.yaml: |
    server:
      port: 50051
      host: "0.0.0.0"
    ratelimiter:
      default-capacity: 100
      default-refill-rate: 1.67
    redis:
      enabled: true
      host: "redis-service"
      port: 6379