// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/ratelimiter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Asks if client can consume tokens
type CheckLimitRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientId        string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TokensRequested int32                  `protobuf:"varint,2,opt,name=tokens_requested,json=tokensRequested,proto3" json:"tokens_requested,omitempty"` // Default=1
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckLimitRequest) Reset() {
	*x = CheckLimitRequest{}
	mi := &file_proto_ratelimiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLimitRequest) ProtoMessage() {}

func (x *CheckLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckLimitRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimiter_proto_rawDescGZIP(), []int{0}
}

func (x *CheckLimitRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckLimitRequest) GetTokensRequested() int32 {
	if x != nil {
		return x.TokensRequested
	}
	return 0
}

// Tells if request is allowed
type CheckLimitResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Allowed         bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	RemainingTokens int32                  `protobuf:"varint,2,opt,name=remaining_tokens,json=remainingTokens,proto3" json:"remaining_tokens,omitempty"`
	RetryAfterMs    int64                  `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` //Time in ms to wait before retry(if rejected)
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckLimitResponse) Reset() {
	*x = CheckLimitResponse{}
	mi := &file_proto_ratelimiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLimitResponse) ProtoMessage() {}

func (x *CheckLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckLimitResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimiter_proto_rawDescGZIP(), []int{1}
}

func (x *CheckLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckLimitResponse) GetRemainingTokens() int32 {
	if x != nil {
		return x.RemainingTokens
	}
	return 0
}

func (x *CheckLimitResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *CheckLimitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_ratelimiter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimiter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimiter_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// returns rate limiter state
type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RemainingTokens int32                  `protobuf:"varint,1,opt,name=remaining_tokens,json=remainingTokens,proto3" json:"remaining_tokens,omitempty"`
	Capacity        int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"` //Bucket Capacity
	RefillRate      float64                `protobuf:"fixed64,3,opt,name=refill_rate,json=refillRate,proto3" json:"refill_rate,omitempty"`
	NextRefillMs    int64                  `protobuf:"varint,4,opt,name=next_refill_ms,json=nextRefillMs,proto3" json:"next_refill_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_ratelimiter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimiter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimiter_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetRemainingTokens() int32 {
	if x != nil {
		return x.RemainingTokens
	}
	return 0
}

func (x *GetStatusResponse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *GetStatusResponse) GetRefillRate() float64 {
	if x != nil {
		return x.RefillRate
	}
	return 0
}

func (x *GetStatusResponse) GetNextRefillMs() int64 {
	if x != nil {
		return x.NextRefillMs
	}
	return 0
}

var File_proto_ratelimiter_proto protoreflect.FileDescriptor

const file_proto_ratelimiter_proto_rawDesc = "" +
	"\n" +
	"\x17proto/ratelimiter.proto\x12\vratelimiter\"[\n" +
	"\x11CheckLimitRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12)\n" +
	"\x10tokens_requested\x18\x02 \x01(\x05R\x0ftokensRequested\"\x99\x01\n" +
	"\x12CheckLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12)\n" +
	"\x10remaining_tokens\x18\x02 \x01(\x05R\x0fremainingTokens\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\x03R\fretryAfterMs\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"/\n" +
	"\x10GetStatusRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xa1\x01\n" +
	"\x11GetStatusResponse\x12)\n" +
	"\x10remaining_tokens\x18\x01 \x01(\x05R\x0fremainingTokens\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x1f\n" +
	"\vrefill_rate\x18\x03 \x01(\x01R\n" +
	"refillRate\x12$\n" +
	"\x0enext_refill_ms\x18\x04 \x01(\x03R\fnextRefillMs2\xa8\x01\n" +
	"\vRateLimiter\x12M\n" +
	"\n" +
	"CheckLimit\x12\x1e.ratelimiter.CheckLimitRequest\x1a\x1f.ratelimiter.CheckLimitResponse\x12J\n" +
	"\tGetStatus\x12\x1d.ratelimiter.GetStatusRequest\x1a\x1e.ratelimiter.GetStatusResponseB2Z0github.com/MKR-24/distributed-rate-limiter/protob\x06proto3"

var (
	file_proto_ratelimiter_proto_rawDescOnce sync.Once
	file_proto_ratelimiter_proto_rawDescData []byte
)

func file_proto_ratelimiter_proto_rawDescGZIP() []byte {
	file_proto_ratelimiter_proto_rawDescOnce.Do(func() {
		file_proto_ratelimiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ratelimiter_proto_rawDesc), len(file_proto_ratelimiter_proto_rawDesc)))
	})
	return file_proto_ratelimiter_proto_rawDescData
}

var file_proto_ratelimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ratelimiter_proto_goTypes = []any{
	(*CheckLimitRequest)(nil),  // 0: ratelimiter.CheckLimitRequest
	(*CheckLimitResponse)(nil), // 1: ratelimiter.CheckLimitResponse
	(*GetStatusRequest)(nil),   // 2: ratelimiter.GetStatusRequest
	(*GetStatusResponse)(nil),  // 3: ratelimiter.GetStatusResponse
}
var file_proto_ratelimiter_proto_depIdxs = []int32{
	0, // 0: ratelimiter.RateLimiter.CheckLimit:input_type -> ratelimiter.CheckLimitRequest
	2, // 1: ratelimiter.RateLimiter.GetStatus:input_type -> ratelimiter.GetStatusRequest
	1, // 2: ratelimiter.RateLimiter.CheckLimit:output_type -> ratelimiter.CheckLimitResponse
	3, // 3: ratelimiter.RateLimiter.GetStatus:output_type -> ratelimiter.GetStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ratelimiter_proto_init() }
func file_proto_ratelimiter_proto_init() {
	if File_proto_ratelimiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ratelimiter_proto_rawDesc), len(file_proto_ratelimiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ratelimiter_proto_goTypes,
		DependencyIndexes: file_proto_ratelimiter_proto_depIdxs,
		MessageInfos:      file_proto_ratelimiter_proto_msgTypes,
	}.Build()
	File_proto_ratelimiter_proto = out.File
	file_proto_ratelimiter_proto_goTypes = nil
	file_proto_ratelimiter_proto_depIdxs = nil
}
